# Generated by Django 2.2.15 on 2020-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='log_in_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
