# Generated by Django 2.2.15 on 2020-08-12 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200812_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
