# Generated by Django 2.2.15 on 2020-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
