# Generated by Django 2.2.15 on 2020-08-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
