# Generated by Django 2.2.15 on 2020-08-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('forward', 'فوروارد')], default=None, max_length=10),
        ),
    ]
