# Generated by Django 2.2.15 on 2020-08-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('forward', 'فوروارد')], max_length=10),
        ),
    ]
