# Generated by Django 2.2.15 on 2020-08-17 03:30

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200817_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='delay_between_msg',
            field=models.PositiveIntegerField(default=5, help_text='delay between each send message', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='telegram accounts id', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('forward', 'فوروارد')], default=None, max_length=10),
        ),
    ]
