# Generated by Django 2.2.15 on 2020-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logged',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
